import React from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Cards from '../components/Cards/Cards'
import Form from '../components/Form/Form';

export default function Home() {
  
  return (
    <React.Fragment>
      <Head>
        <title>Next ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <Form/>
        <Cards/>
      </div>
    </React.Fragment>
  )
}
